/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app/payments/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppMaintenancesIndexRouteImport } from './routes/_app/maintenances/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products/$productId'
import { Route as AppPaymentsUnpaidRouteImport } from './routes/_app/payments/unpaid'
import { Route as AppOrdersOverdueRouteImport } from './routes/_app/orders/overdue'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'
import { Route as AppOrdersActiveRouteImport } from './routes/_app/orders/active'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders/$id'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers/new'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaintenancesIndexRoute = AppMaintenancesIndexRouteImport.update({
  id: '/maintenances/',
  path: '/maintenances/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsUnpaidRoute = AppPaymentsUnpaidRouteImport.update({
  id: '/payments/unpaid',
  path: '/payments/unpaid',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersOverdueRoute = AppOrdersOverdueRouteImport.update({
  id: '/orders/overdue',
  path: '/orders/overdue',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersActiveRoute = AppOrdersActiveRouteImport.update({
  id: '/orders/active',
  path: '/orders/active',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/active': typeof AppOrdersActiveRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/orders/overdue': typeof AppOrdersOverdueRoute
  '/payments/unpaid': typeof AppPaymentsUnpaidRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/maintenances/': typeof AppMaintenancesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/active': typeof AppOrdersActiveRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/orders/overdue': typeof AppOrdersOverdueRoute
  '/payments/unpaid': typeof AppPaymentsUnpaidRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/maintenances': typeof AppMaintenancesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/active': typeof AppOrdersActiveRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/orders/overdue': typeof AppOrdersOverdueRoute
  '/_app/payments/unpaid': typeof AppPaymentsUnpaidRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/maintenances/': typeof AppMaintenancesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/new'
    | '/orders/$id'
    | '/orders/active'
    | '/orders/new'
    | '/orders/overdue'
    | '/payments/unpaid'
    | '/products/$productId'
    | '/products/new'
    | '/categories/'
    | '/customers/'
    | '/inventory/'
    | '/maintenances/'
    | '/orders/'
    | '/payments/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/new'
    | '/orders/$id'
    | '/orders/active'
    | '/orders/new'
    | '/orders/overdue'
    | '/payments/unpaid'
    | '/products/$productId'
    | '/products/new'
    | '/categories'
    | '/customers'
    | '/inventory'
    | '/maintenances'
    | '/orders'
    | '/payments'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/customers/new'
    | '/_app/orders/$id'
    | '/_app/orders/active'
    | '/_app/orders/new'
    | '/_app/orders/overdue'
    | '/_app/payments/unpaid'
    | '/_app/products/$productId'
    | '/_app/products/new'
    | '/_app/categories/'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/maintenances/'
    | '/_app/orders/'
    | '/_app/payments/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/maintenances/': {
      id: '/_app/maintenances/'
      path: '/maintenances'
      fullPath: '/maintenances/'
      preLoaderRoute: typeof AppMaintenancesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/payments/unpaid': {
      id: '/_app/payments/unpaid'
      path: '/payments/unpaid'
      fullPath: '/payments/unpaid'
      preLoaderRoute: typeof AppPaymentsUnpaidRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/overdue': {
      id: '/_app/orders/overdue'
      path: '/orders/overdue'
      fullPath: '/orders/overdue'
      preLoaderRoute: typeof AppOrdersOverdueRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/active': {
      id: '/_app/orders/active'
      path: '/orders/active'
      fullPath: '/orders/active'
      preLoaderRoute: typeof AppOrdersActiveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersActiveRoute: typeof AppOrdersActiveRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppOrdersOverdueRoute: typeof AppOrdersOverdueRoute
  AppPaymentsUnpaidRoute: typeof AppPaymentsUnpaidRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppMaintenancesIndexRoute: typeof AppMaintenancesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersActiveRoute: AppOrdersActiveRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppOrdersOverdueRoute: AppOrdersOverdueRoute,
  AppPaymentsUnpaidRoute: AppPaymentsUnpaidRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppMaintenancesIndexRoute: AppMaintenancesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
