import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

type Migration = {
	name: string;
	checksum: string;
	sql: string;
};

async function main() {
	const serverRoot = resolve(import.meta.dirname, "..");
	const migrationsDir = join(serverRoot, "prisma", "migrations");
	const outFile = join(serverRoot, "src", "bootstrap", "migrations.generated.ts");

	const entries = await readdir(migrationsDir, { withFileTypes: true });
	const migrationNames = entries
		.filter((e) => e.isDirectory())
		.map((e) => e.name)
		.sort();

	const migrations: Migration[] = [];
	for (const name of migrationNames) {
		const sqlPath = join(migrationsDir, name, "migration.sql");
		const sql = await readFile(sqlPath, "utf8");
		const checksum = createHash("sha256").update(sql, "utf8").digest("hex");
		migrations.push({ name, checksum, sql });
	}

	const header = `// This file is generated by server/scripts/generate-migrations.ts\n// Do not edit by hand.\n\n`;
	const body =
		`export const MIGRATIONS = ${JSON.stringify(migrations, null, 2)} as const;\n`;

	await writeFile(outFile, header + body, "utf8");
	console.info(`[generate-migrations] Wrote ${migrations.length} migrations to ${outFile}`);
}

main().catch((err) => {
	console.error("[generate-migrations] Failed:", err);
	process.exit(1);
});

